### ISSUE TITLE
SpringsUI.Refresh Node crashes Dynamo every time

### ISSUE THREAD

**Issue by JosefRadi** [dimven/SpringNodes#47]
Here is the Issue:
https://github.com/DynamoDS/Dynamo/issues/8943#issuecomment-400073060

Maybe the Node is not updated for 2.0?

**Comment by dimven** [comment]
Hi,

I haven't gotten around to converting the UI package to 2.0 yet, because the changes to the NodeModel API are pretty extensive. Tho interestingly I can't reproduce this behavior. I tested it in 2.0.1. Are you using the latest version of the package?

**Comment by JosefRadi** [comment]
I loaded the package last week so should be updated? 
I loaded it from Dynamo. Is this right or do I have to load it from Github?

Did you also Press on the button "Refresh" ?
As soon I press this Button my Dynamo crashes...

**Comment by dimven** [comment]
2.0.1 and Revit 2018 seem to work fine:
![2018-06-27_23-06-57](https://user-images.githubusercontent.com/7148394/41982910-31e47880-7a5f-11e8-8a09-03e1b83f9a98.gif)

**Comment by JosefRadi** [comment]
@dimven I also have Dynamo 1.3.2 - here it worked like as your video. 

But as soon I try with Dynamo 2.0.1 and press on Refresh it crashes

**Comment by ghost** [comment]
I am having the same issue, trying to work through updating our package library to 2.0 friendly nodes. 

I have included a screenshot and details of the Dynamo error.

![image](https://user-images.githubusercontent.com/26099702/46749857-3f9c0280-cc7c-11e8-9a12-a82431da2be4.png)

Here is a copy of details from the error:

Field not found: 'Dynamo.Graph.Workspaces.HomeWorkspaceModel.RunSettings'.

   at SpringsUI.RefreshButton.Flip()
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
